---
version: 2
jobs:
  node-12: &test
    docker:
      - image: node:12
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Create profile
          command: npx zowe profiles create zosmf-profile zzow01-zowep --host zzow01.zowe.marist.cloud --port 10443 --user zowep --pass $ZOWEP_PASSWORD --reject-unauthorized false
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: npm test
      - run:
          name: Sample Perf Testing
          command: npm run perftest
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publishing zztop Tool to npmjs.com
          command: |
            git config --global user.email "plavjanik@gmail.com"
            git config --global user.name "Petr Plavjanik"
            npm version --no-git-tag-version `git describe --tags --abbrev=0 | cut -c2-`
            npm pack
            echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > ~/.npmrc
            npm publish --access public
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "zztop":
    jobs:
      - node-12
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
